name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: cppcheck-action
          uses: deep5050/cppcheck-action@v3.0
        - name: publish report    
          uses: mikeal/publish-to-github-action@master
          env:
            BRANCH_NAME: 'master'
