name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: cppcheck-action
          uses: deep5050/cppcheck-action@v3.0
          with:
            enable: warning,performance,stability,information,missingInclude
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: cppcheck report
            path: cppcheck_report.txt

