name: Build and publish Doxygen docs
on:
  release:
    types: published
jobs: 
  build-docs:
    name: Build doxygen docs
      steps:
        - uses: lukka/get-cmake@latest
        - uses: actions/checkout@v2
        - uses: lukka/run-cmake@v10
