name: Build and publish Doxygen docs
on:
  release:
    types: published

jobs: 
  build-docs:
    runs-on: ubuntu-latest
    name: Build doxygen docs
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/examples/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_DOC=ON
      - name: Build doxygen docs
        run: cmake --build ${{github.workspace}}/examples/build --config ${{env.BUILD_TYPE}}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc_doxygen/

